[[redirects]]
  from = "/api/*"
  to = "https://mentorsphilippines.sandbox.mambu.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"}
