[[redirects]]
  from = "/api/*"
  to = "https://mentorsphilippines.sandbox.mambu.com/api/:splat"
  status = 200
  force = true
  headers = {Authorization = "${BASIC_AUTH}"}


[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"